# Generated by Django 6.1 on 2026-08-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_broadcast_broadcastrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(help_text="Use {{1}}, {{2}}, etc. as placeholders, in order — this matches WhatsApp's own numbered-variable format exactly (not named placeholders), since that's what Meta's template system actually requires."),
        ),
    ]
