# Generated by Django 6.1 on 2026-08-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='department',
            field=models.CharField(default='GENERAL', max_length=20),
        ),
    ]
