# Generated by Django 6.1 on 2026-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_message_deleted_at_message_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'Agent'), ('SYSTEM', 'System'), ('BOT', 'Bot'), ('PHONE', 'Phone (sent outside the CRM)')], max_length=10),
        ),
    ]
