# Generated by Django 6.1 on 2026-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_internalmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmessage',
            name='file_mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='internalmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
