# Generated by Django 6.1 on 2026-08-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lead_outcome',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
