# Generated by Django 6.1 on 2026-08-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_lead_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lead_outcome_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
